#!/bin/bash

if [[ "$#" -ne 1 ]]
then
  echo Exactly 1 argument required
  return 1
fi

if [[ -n $NOTE_EDITOR ]]
then editor=$NOTE_EDITOR
elif [[ -n $EDITOR ]]
then editor=$EDITOR
else editor=vi
fi

$editor "$(note-dir)/$1"
